### PR TITLE
Fix issue 175 by replacing deprecated getsize function

### LINKED ISSUE #175: AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Looks like the `getsize()` method is deprecated in Pillow 10.0.0, so the examples that use it will need updating.

In the meantime, it works if you roll back to an older version of Pillow:

`pip install Pillow==9.5.0`

### PR DESCRIPTION
**Pull request by trepidacious**
Fix #175 

`font.getsize` can be replaced with a simple function calling through to `font.getbbox`. This seems to give very similar results, testing with a few quotes the size was almost always identical, sometimes different by 1 pixel.

This allows the updated examples to work with Pillow 10.x

### CODE REVIEW

**Comment by neozenith** [comment]
Can confirm the `getbbox` works with Inky pHAT Red and `pillow==10.1.0`.

Since:
- `getsize` was deprecated in 9.2.0 and end-of-life <10
- `getbbox` was only made available from 9.2.0

https://pillow.readthedocs.io/en/stable/releasenotes/9.2.0.html#font-size-and-offset-methods

Would the following help:

```python
def getsize(font, text):
    try:
        # pillow>=9.2.0
        # https://pillow.readthedocs.io/en/stable/releasenotes/9.2.0.html#font-size-and-offset-methods
        _, _, right, bottom = font.getbbox(text)
        return (right, bottom)
    except AttributeError:
        # Legacy fallback method
        # pillow<10
        return font.getsize(text)
```

**Comment by Gadgetoid** [comment]
Thank you!
